config/routes.rb
Rails.application.routes.draw do
  resources :docs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = Doc.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doc_params
      params.require(:doc).permit(:type, :number, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.haml
= form_with(model: doc, local: true) do |form|
  - if doc.errors.any?
    #error_explanation
      %h2
        = pluralize(doc.errors.count, "error")
        prohibited this doc from being saved:
      %ul
        - doc.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :type
    = form.text_field :type
  .field
    = form.label :number
    = form.text_field :number
  .field
    = form.label :name
    = form.text_area :name
  .actions
    = form.submit

app/views/docs/edit.html.haml
%h1 Editing Doc
= render 'form', doc: @doc
= link_to 'Show', @doc
|
= link_to 'Back', docs_path

app/views/docs/index.html.haml
%p#notice= notice
%h1
  Docs
  %i.fa.fa-flag{"aria-hidden" => "true"}
%table
  %thead
    %tr
      %th Type
      %th Number
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @docs.each do |doc|
      %tr
        %td= doc.type
        %td= doc.number
        %td= doc.name
        %td= link_to 'Show', doc
        %td= link_to 'Edit', edit_doc_path(doc)
        %td= link_to 'Destroy', doc, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Doc', new_doc_path

app/views/docs/new.html.haml
%h1 New Doc
= render 'form', doc: @doc
= link_to 'Back', docs_path

app/views/docs/show.html.haml
%p#notice= notice
%p
  %strong Type:
  = @doc.type
%p
  %strong Number:
  = @doc.number
%p
  %strong Name:
  = @doc.name
= link_to 'Edit', edit_doc_path(@doc)
|
= link_to 'Back', docs_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ebase
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield